<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="css/estilo.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
  

    <div class="caixa d-flex justify-content-center">
        <div id="formulario">
            <form action="/login" method="post">

                <h3>Login de usuário</h3>
                <hr>

                <label for="nome">Login</label>
                <input type="text" placeholder="Login de Usuário" class="form-control mt-2" name="nome">
                <label for="nome">Senha</label>
                <input type="password" placeholder="Senha de Usuário" class="form-control mt-2" name="senha">
                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary mt-4">Fazer Login</button>
                </div>
                <div>
                    <a class="link-personalizado" href="/cadastrar">Cadastrar Usuario</a>
                    <a class="link-personalizado" href="/lembrar">Esqueceu Senha?</a>
                </div>

            </form>
        </div>
    </div>
    



<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>